// packages/shared-ui/src/components/Composer.tsx
/**
 * Composer — message input for the DSH UI kit.
 * @module @dsh-platform/shared-ui/components
 */
import { useState, type DragEvent, type KeyboardEvent } from 'react'

export interface ComposerProps {
  disabled?: boolean
  placeholder?: string
  /** Async submit; parent decides transport (bridge / remote / local DSH). */
  onSubmit?: (text: string) => void | Promise<void>
  onDropFiles?: (files: Array<{ name: string; data: string }>) => void
}

export function Composer({
  disabled,
  placeholder = '输入消息，Enter 发送，Shift+Enter 换行',
  onSubmit,
  onDropFiles
}: ComposerProps) {
  const [text, setText] = useState('')
  const [sending, setSending] = useState(false)

  async function send() {
    const value = text.trim()
    if (!value || disabled || sending) return
    setSending(true)
    try {
      await onSubmit?.(value)
      setText('')
    } finally {
      setSending(false)
    }
  }

  function onKeydown(event: KeyboardEvent<HTMLTextAreaElement>) {
    if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing) {
      event.preventDefault()
      void send()
    }
  }

  async function onDrop(event: DragEvent<HTMLDivElement>) {
    const items = Array.from(event.dataTransfer?.items ?? []).filter((item) => item.kind === 'file')
    if (items.length === 0) return
    event.preventDefault()
    const files: Array<{ name: string; data: string }> = []
    for (const item of items) {
      const file = item.getAsFile()
      if (!file) continue
      const dataUrl = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader()
        reader.onload = () => resolve(String(reader.result))
        reader.onerror = () => reject(reader.error)
        reader.readAsDataURL(file)
      })
      files.push({ name: file.name, data: dataUrl })
    }
    onDropFiles?.(files)
  }

  return (
    <footer className="dsh-composer">
      <div className="dsh-composer__drop" onDragOver={(e) => e.preventDefault()} onDrop={onDrop}>
        <textarea
          className="dsh-textarea dsh-composer__input"
          placeholder={placeholder}
          disabled={disabled}
          rows={2}
          value={text}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={onKeydown}
        />
        <div className="dsh-composer__actions">
          <button
            className="dsh-button dsh-button--primary"
            disabled={disabled || text.trim().length === 0 || sending}
            onClick={send}
          >
            {sending ? '发送中…' : '发送'}
          </button>
        </div>
      </div>
    </footer>
  )
}

// packages/shared-ui/src/components/Composer.vue
<script setup lang="ts">
import { ref } from 'vue'

const props = withDefaults(
  defineProps<{
    disabled?: boolean
    placeholder?: string
    /** Async submit; parent decides transport (bridge / remote / local DSH). */
    onSubmit?: (text: string) => void | Promise<void>
  }>(),
  { placeholder: '输入消息，Enter 发送，Shift+Enter 换行' }
)

const emits = defineEmits<{
  (e: 'submit', text: string): void
  (e: 'drop-files', files: Array<{ name: string; data: string }>): void
}>()

const text = ref('')
const sending = ref(false)

async function send() {
  const value = text.value.trim()
  if (!value || props.disabled || sending.value) return
  sending.value = true
  try {
    await props.onSubmit?.(value)
    emits('submit', value)
    text.value = ''
  } finally {
    sending.value = false
  }
}

function onKeydown(event: KeyboardEvent) {
  if (event.key === 'Enter' && !event.shiftKey && !event.isComposing) {
    event.preventDefault()
    void send()
  }
}

async function onDrop(event: DragEvent) {
  const items = Array.from(event.dataTransfer?.items ?? []).filter((item) => item.kind === 'file')
  if (items.length === 0) return
  event.preventDefault()
  const files: Array<{ name: string; data: string }> = []
  for (const item of items) {
    const file = item.getAsFile()
    if (!file) continue
    // Read as data URL; large files should go through the native file-drop bridge.
    const dataUrl = await new Promise<string>((resolvePromise, reject) => {
      const reader = new FileReader()
      reader.onload = () => resolvePromise(String(reader.result))
      reader.onerror = () => reject(reader.error)
      reader.readAsDataURL(file)
    })
    files.push({ name: file.name, data: dataUrl })
  }
  emits('drop-files', files)
}
</script>

<template>
  <footer class="dsh-composer">
    <div
      class="dsh-composer__drop"
      @dragover.prevent
      @drop.prevent="onDrop"
    >
      <textarea
        v-model="text"
        class="dsh-textarea dsh-composer__input"
        :placeholder="placeholder"
        :disabled="disabled"
        rows="2"
        @keydown="onKeydown"
      />
      <div class="dsh-composer__actions">
        <button
          class="dsh-button dsh-button--primary"
          :disabled="disabled || text.trim().length === 0 || sending"
          @click="send"
        >
          {{ sending ? '发送中…' : '发送' }}
        </button>
      </div>
    </div>
  </footer>
</template>

<style scoped>
.dsh-composer {
  border-top: 1px solid var(--dsh-border);
  padding: var(--dsh-gap-m);
  background: var(--dsh-bg-elevated);
}
.dsh-composer__drop {
  display: flex;
  gap: var(--dsh-gap-s);
  align-items: flex-end;
}
.dsh-composer__input {
  flex: 1;
  resize: none;
}
.dsh-composer__actions {
  display: flex;
  gap: var(--dsh-gap-s);
}
</style>
